---
trigger:
  branches:
    include:
      - quality
resources:
  - repo: self
variables:
  - group: PipelineVarsQA
stages:
  - stage: CI
    displayName: "Continuos Deploy QA"
    jobs:
      - job: CI
        displayName: "Continuos Deploy QA Job"
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: "Build Docker"
            inputs:
              repository: "$(AWS_Container_Repository)"
              command: "build"
              Dockerfile: "**/Dockerfile"
              tags: "$(tagBilling)"
          - script: |
              docker images
            displayName: "Docker images"
          - task: ECRPushImage@1
            displayName: "Push Image AWS"
            inputs:
              awsCredentials: "AWS-SC-recruitMasterUser"
              regionName: "us-east-1"
              imageSource: "imagename"
              sourceImageName: "$(AWS_Container_Repository)"
              sourceImageTag: "$(tagBilling)"
              repositoryName: "$(AWS_Container_Repository)"
              pushTag: "$(tagBilling)"
